apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      imagePullSecrets:       # 👈 이 줄 추가
      - name: regcred         # 👈 이 줄 추가    
      containers:
      - name: petclinic
        image: 450444046629.dkr.ecr.ca-central-1.amazonaws.com/user21-cluster:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
